### ISSUE TITLE
Pagination of archives

### ISSUE THREAD

**Issue by onetrev** [jacklenox/archives-for-custom-post-types#1]
Very excited to see this plugin, thank you for getting this rolling! Just one small, but key issue, I don't think pagination works for the archives pages. 

ex: /2014/postname_type/page/2/

This results in a 404. I found the same issue with an old CPT Archives plugin, but this post had a fix for it. Not sure if it would help resolve the issue for this plugin, but here is the link: http://wordpress.org/support/topic/plugin-custom-post-type-archives-paging-problem-with-yearlymonthly-archives?replies=4

Thanks!
Trevor

**Comment by jacklenox** [comment]
Argh, thanks Trevor. There's a very straightforward fix to this. I just need to add some more rewrite rules.

Thanks for reporting this. I'll get it patched and commit 1.0.2 as soon as I get a minute.

Incidentally, I don't think I came across that particular plugin. Hmm, is there anything mine does that that one doesn't...?

One thing I do intend to add is a widget that will allow you to choose your active post types from a dropdown (it'll otherwise work like the standard archive widget).

Cheers,

Jack

**Comment by onetrev** [comment]
Great to hear you can fix this without too much trouble. Regarding that other plugin, no, there is nothing else it does that your plugin needs I think. It mostly was for allowing archives for custom post types back when WP didn't support them at all at first.

The only thing extra it does is allow you to create custom permalinks for CPTs, but that can be easily done when you create the CPT in your code, so I don't think it is needed at all.

I like your idea of enabling widget support for custom post type archives, great for those who don't custom code at all.

Thanks again for your work on this.
Trevor
